### ISSUE TITLE
Personal details/ Biographies

### ISSUE THREAD

**Issue by Nyasita** [Nyasita/HackBioAssignmentPauling#2]
Hello everyone,
If you haven't already...
Please update your biography under contributors on the readme, complete with:

1. Your name
2. What you do/ affiliation
3. Your social media handles/ github profile
4. An image of yourself

**Comment by SuliJimoh** [comment]
done

**Comment by OYEFAVOUR** [comment]
![OYEFAVOUR](https://user-images.githubusercontent.com/46101497/128259086-923b80d3-40c6-4e86-b798-ab3a3ddb2c1d.jpg)

## 14.  Favour Oluwapelumi OYELAMI

Medical Research Writer (Cancer Genomics)/ MSc graduate of Animal Science (Statistical Genomics and Bioinformatics) 

I am interested in delivering precision medicine for underrepresented populations through genomics. I also hope to dive into the application of A.I and M.L to cancer genomics.

:link: Let's connect on [LinkedIn](https://www.linkedin.com/in/oyelami-favour-oluwapelumi-6b9397126) and [Twitter](https://twitter.com/OYEFAVOUR)
